# 尝试和捕获

> 原文:[https://www.learnjavaonline.org/en/Try_and_Catch](https://www.learnjavaonline.org/en/Try_and_Catch)

* * *

在进入 try/catch 语句之前，我们先来谈谈异常。每次发生错误时都会引发异常。一些例子:*如果访问了数组中不存在的索引，则抛出 ArrayIndexOutOfBounds(例如:试图访问 arr[5]，但 arr 仅上升到 arr[4])* 如果进行了非法的算术运算，则抛出算术错误(例如:42/0，除以零)

Java 可以抛出许多异常(不止上述情况)。

但是，当您不确定是否会发生错误时，如何处理异常呢？

这就是 try/catch 的目的！try/catch 的语法如下:

```py
 try {
    //Code here
  } catch (ExceptionHere name) {
        //Replace ExceptionHere with your exception and name with the name of your exception.
        //Code if exception "ExceptionHere" is thrown.
  } 
```

将尝试运行 try 块之后的代码。如果在运行 try 块中的代码期间引发 catch 语句中的异常，请运行 catch 块中的代码。

你可以告诉用户有问题，或者别的什么。

注意:如果抛出任何异常，也可以使用 Exception 作为异常来捕获。

## 锻炼

在本练习中，您将尝试捕捉有问题的代码。我将创建一个有问题的代码块。我希望您将有问题的代码包装在 try 块中，然后如果抛出异常，让它打印“检测到代码有问题”。

注意:使用 ArrayIndexOutOfBoundsException 作为异常，或者使用 Exception 作为异常。